SELECT * FROM dbo.CovidDeaths

--1) SHOW LIKELIYHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY
SELECT LOCATION, DATE, total_cases, total_deaths, ROUND((total_deaths/total_cases)*100,2) as DEATH_PERCENTAGES
FROM dbo.CovidDeaths
WHERE location = 'India' AND continent IS NOT NULL
ORDER BY 1, 2

--2) SHOWS WHAT PERCENTAGE OF TOTAL POPULATION IS SFFECTED WITH COVID. LOOKING AT TOATL CASES VS POPULATION
SELECT LOCATION, DATE, total_cases, population, ROUND((total_cases/population)*100,2) as PERCENT_OF_POPULATION_INFECTED
FROM dbo.CovidDeaths
WHERE location = 'India' AND continent IS NOT NULL
ORDER BY 1, 2

--3) LOOKING AT COUNTRY WITH HIGHEST INFECTION RATE AS COMPAIRED TO POPULATION
SELECT location, population, MAX(TOTAL_CASES) AS HIGHEST_INFECTION_COUNT, MAX(ROUND((total_cases/population)*100,2)) as PERCENT_OF_POPULATION_INFECTED
FROM DBO.CovidDeaths
WHERE continent IS NOT NULL
GROUP BY location, population
ORDER BY PERCENT_OF_POPULATION_INFECTED DESC

--4) SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION
SELECT location, MAX(CAST(total_deaths AS INT)) AS TOTAL_DEATH_COUNT
FROM DBO.CovidDeaths
WHERE continent IS NOT NULL
GROUP BY location
ORDER BY TOTAL_DEATH_COUNT DESC

--5) SHOWING CONTINENT WITH HIGHEST DEATH COUNT PER POPULATION
SELECT continent, MAX(CAST(total_deaths AS INT)) AS TOTAL_DEATH_COUNT
FROM DBO.CovidDeaths
WHERE continent IS NOT NULL
GROUP BY continent
ORDER BY TOTAL_DEATH_COUNT DESC

--6) GLOBAL NUMBER
SELECT DATE, SUM(new_cases) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, ROUND(SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100,2) AS DEATH_PERCENTAGES
FROM dbo.CovidDeaths
WHERE continent IS NOT NULL
GROUP BY date
ORDER BY 1, 2

--7) LOOKING AT TOTAL POPULATION VS VACCINATIONS
WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLING_PPL_VACCINATED)
AS (
SELECT DEA.continent, DEA.location, DEA.date, DEA.population, CAST(VAC.new_vaccinations AS INT) AS NEW_VACCINATIONS, 
		SUM(CAST(VAC.new_vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLING_PPL_VACCINATED
FROM dbo.CovidDeaths AS DEA
JOIN dbo.CovidVaccinations AS VAC
ON DEA.date = VAC.date AND DEA.location = VAC.location
WHERE DEA.continent IS NOT NULL 
--ORDER BY 2,3
)
SELECT *, ROUND((ROLLING_PPL_VACCINATED/POPULATION)*100,2) AS PERCENTAGE_VACCINATED FROM POPVSVAC
 
--USING TEMP TABLE
DROP TABLE IF EXISTS #PERCENT_POPULATION_VACCINATED
CREATE TABLE #PERCENT_POPULATION_VACCINATED
(
CONTINENT VARCHAR(255), 
LOCATION VARCHAR(255), 
DATE DATETIME, 
POPULATION NUMERIC, 
NEW_VACCINATIONS NUMERIC, 
ROLLING_PPL_VACCINATED NUMERIC
)
INSERT INTO #PERCENT_POPULATION_VACCINATED
SELECT DEA.continent, DEA.location, DEA.date, DEA.population, CAST(VAC.new_vaccinations AS INT) AS NEW_VACCINATIONS, 
		SUM(CAST(VAC.new_vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLING_PPL_VACCINATED
FROM dbo.CovidDeaths AS DEA
JOIN dbo.CovidVaccinations AS VAC
ON DEA.date = VAC.date AND DEA.location = VAC.location
WHERE DEA.continent IS NOT NULL 

SELECT *, ROUND((ROLLING_PPL_VACCINATED/POPULATION)*100,2) AS PERCENTAGE_VACCINATED FROM #PERCENT_POPULATION_VACCINATED


-- CREATING VIEWS
CREATE VIEW PERCENT_POPULATION_VACCINATED AS
SELECT DEA.continent, DEA.location, DEA.date, DEA.population, CAST(VAC.new_vaccinations AS INT) AS NEW_VACCINATIONS, 
		SUM(CAST(VAC.new_vaccinations AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLING_PPL_VACCINATED
FROM dbo.CovidDeaths AS DEA
JOIN dbo.CovidVaccinations AS VAC
ON DEA.date = VAC.date AND DEA.location = VAC.location
WHERE DEA.continent IS NOT NULL 

CREATE VIEW GLOBAL_NUMBER AS 
SELECT DATE, SUM(new_cases) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, ROUND(SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100,2) AS DEATH_PERCENTAGES
FROM dbo.CovidDeaths
WHERE continent IS NOT NULL
GROUP BY date


